Reverting menu_breadcrumb
drupalwxt/wxt pull request #156
Opened 2019-03-24 00:18 UTC by RabiaSajjad

Problem with version 1.8 https://www.drupal.org/project/menu_breadcrumb/issues/3042459

2019-03-24 19:35 UTC, zachomedia commented
@RabiaSajjad If we decide to rollback, the `^` will have to be removed from the version number otherwise it will just update to the new version.

2019-03-24 19:54 UTC, zachomedia requested changes

2019-03-24 19:54 UTC, zachomedia commented on composer.json
> +        "drupal/menu_breadcrumb": "^1.7",
If we decide to rollback, the `^` will have to be removed from the version number otherwise it will just update to the new version.

2019-03-26 02:06 UTC, sylus commented
Reverted the module increment and will add mention in KNOWN_ISSUES.md for the moment.

2019-03-26 02:06 UTC, closed without merging